"use client";
import React, { useState, useEffect } from "react";
import {
  useEthereum,
  useConnect,
  useAuthCore,
} from "@particle-network/auth-core-modal";
import { BaseSepolia } from "@particle-network/chains";
import { ethers } from "ethers";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  const { connect, disconnect, connectionStatus } = useConnect();
  const { address, provider } = useEthereum();

  const { userInfo } = useAuthCore();

  const [balance, setBalance] = useState<string>("");

  const customProvider = new ethers.providers.Web3Provider(provider, "any");

  useEffect(() => {
    if (userInfo) {
      fetchBalance();
    }
  }, [userInfo]);

  const fetchBalance = async () => {
    const balanceResponse = await customProvider.getBalance(
      await customProvider.getSigner().getAddress()
    );
    setBalance(ethers.utils.formatEther(balanceResponse));
  };

  const handleLogin = async () => {
    if (!userInfo) {
      await connect({});
    }
  };

  const handleDisconnect = async () => {
    try {
      await disconnect();
    } catch (error) {
      console.error(error);
    }
  };

  const executeUserOp = async () => {
    // Implement the transaction logic here
  };

  return (
    <div className="min-h-screen flex flex-col items-center justify-between p-8 bg-gray-900 text-white">
      <Head>
        <title>Particle Auth Core App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex-grow flex flex-col items-center justify-center w-full max-w-4xl mx-auto">
        {!userInfo ? (
          <div className="login-section">
            <button
              className="bg-purple-600 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded-full transition duration-300 ease-in-out transform hover:scale-105 shadow-lg"
              onClick={handleLogin}
            >
              Sign in with Particle
            </button>
          </div>
        ) : (
          <div className="bg-gray-800 p-6 rounded-lg shadow-lg text-center">
            <h2 className="text-lg font-semibold mb-2 text-white">
              {connectionStatus}
            </h2>
            <h2 className="text-2xl font-semibold mb-2 text-white">
              {userInfo.name}
            </h2>
            <h3 className="text-xl mb-2 text-gray-400">
              {BaseSepolia.fullname}
            </h3>
            <h3 className="text-xl font-semibold text-purple-400">
              {balance} {BaseSepolia.nativeCurrency.symbol}
            </h3>
            <button
              className="mt-4 bg-red-600 hover:bg-red-700 text-white font-bold py-2 px-4 rounded-full transition duration-300 ease-in-out transform hover:scale-105 shadow-lg"
              onClick={handleDisconnect}
            >
              Disconnect
            </button>
          </div>
        )}

        <h1 className="text-4xl font-bold mt-12 mb-6 text-center">
          Welcome to{" "}
          <a
            href="https://particle.network"
            className="text-purple-400 hover:text-purple-300 transition duration-300"
          >
            Particle Network!
          </a>
        </h1>

        <h2 className="text-2xl font-bold mt-4 mb-6 text-center">
          <a
            href="https://github.com/soos3d/particle-next-starter"
            className="text-white hover:text-purple-300 transition duration-300 flex items-center"
          >
            <img
              src="https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png"
              alt="GitHub Logo"
              className="w-6 h-6 mr-2"
            />
            Check the repository
          </a>
        </h2>

        <p className="text-xl mb-12 text-center">
          Get started by editing{" "}
          <code className="bg-gray-800 rounded-md p-1 text-purple-300">
            src/app/page.tsx
          </code>
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 w-full">
          <a
            href="https://docs.particle.network"
            className="border border-purple-500 p-6 rounded-lg hover:bg-gray-800 transition duration-300 ease-in-out transform hover:scale-105"
          >
            <h2 className="text-2xl font-semibold mb-2 text-purple-400">
              Documentation &rarr;
            </h2>
            <p className="text-gray-300">
              Find in-depth information about AuthCore features and API.
            </p>
          </a>

          <a
            href="https://dashboard.particle.network"
            className="border border-purple-500 p-6 rounded-lg hover:bg-gray-800 transition duration-300 ease-in-out transform hover:scale-105"
          >
            <h2 className="text-2xl font-semibold mb-2 text-purple-400">
              Dashboard &rarr;
            </h2>
            <p className="text-gray-300">
              Manage your projects and team, View analytics data, Custom
              configuration.
            </p>
          </a>

          <a
            href="https://github.com/Particle-Network/particle-web-auth-core"
            className="border border-purple-500 p-6 rounded-lg hover:bg-gray-800 transition duration-300 ease-in-out transform hover:scale-105"
          >
            <h2 className="text-2xl font-semibold mb-2 text-purple-400">
              Examples &rarr;
            </h2>
            <p className="text-gray-300">
              Discover and deploy boilerplate example AuthCore projects.
            </p>
          </a>

          <a
            href="https://particle.network"
            className="border border-purple-500 p-6 rounded-lg hover:bg-gray-800 transition duration-300 ease-in-out transform hover:scale-105"
          >
            <h2 className="text-2xl font-semibold mb-2 text-purple-400">
              Website &rarr;
            </h2>
            <p className="text-gray-300">
              Particle Network, The Intent-Centric Modular Access Layer of Web3.
            </p>
          </a>
        </div>
      </main>

      <footer className="w-full flex justify-center items-center py-8">
        <Image src="/dark.png" alt="Particle Logo" width={240} height={24} />
      </footer>
    </div>
  );
};

export default Home;
